kind: PersistentVolume
apiVersion: v1
metadata:
  name: alertmanager-pv
  namespace: monitoring 
  labels:
    type: local
spec:
  storageClassName: alertmanager
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
     path: "/data/prometheus/alertmanager"
