kind: PersistentVolume
apiVersion: v1
metadata:
  name: pushgateway-pv
  namespace: monitoring 
  labels:
    type: local
spec:
  storageClassName: pushgateway
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
     path: "/data/prometheus/pushgateway"
